const NewsSlides = [
	{
		id: 1,
		img: 'news1.jpg',
		title: '10 tell-tale signs you need to get a new business',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per1.jpg',
		tag: 'lifestyle',
	},
	{
		id: 2,
		img: 'news2.jpg',
		title: 'This is why this year will be the year of startups',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per2.jpg',
		tag: 'Business',
	},
	{
		id: 3,
		img: 'news3.jpg',
		title: 'Best Pinterest Boards for learning about business',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per3.jpg',
		tag: 'sport',
	},
	{
		id: 4,
		img: 'news4.jpg',
		title: '7 common mistakes everyone makes while traveling',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per4.jpg',
		tag: 'technology',
	},
	{
		id: 5,
		img: 'news5.jpg',
		title: 'Skills that you can learn from business',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per5.jpg',
		tag: 'Business',
	},
	{
		id: 6,
		img: '03.jpg',
		title: 'The pros and cons of business agency',
		autor: 'John Doe',
		date: 'Jun 01, 2022',
		autor_img: 'per6.jpg',
		tag: 'lifestyle',
	},
];
export default NewsSlides;
