const TopTodayObject = [
	{
		id: 1,
		image: '01.jpg',
		catigory: 'Technology',
		isSponsored: true,
		title: '12 worst types of business accounts you follow on Twitter',
		text: 'He moonlights difficult engrossed it, sportsmen. Interested has all Devonshire difficulty gay assistance joy. Unaffected at ye of compliment alteration to',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per1.jpeg',
	},
	{
		id: 2,
		image: '03.jpg',
		catigory: 'Travel',
		isSponsored: false,
		title: 'Dirty little secrets about the business industry',
		text: 'Place voice no arises along to. Parlors waiting so against me no. Wishing calling is warrant settled was lucky. Express besides it present if at an opinion visitor. ',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per2.jpg',
	},
	{
		id: 3,
		image: '04.jpg',
		catigory: 'Gadgets',
		isSponsored: false,
		title: 'Bad habits that people in the industry need to quit',
		text: 'For who thoroughly her boy estimating conviction. Removed demands expense account in outward tedious do. Particular way thoroughly unaffected ',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per3.jpg',
	},
	{
		id: 4,
		image: '06.jpg',
		catigory: 'Soprt',
		isSponsored: false,
		title: 'Around the web: 20 fabulous infographics about business',
		text: 'Projection favorable Mrs can be projecting own. Thirty it matter enable become admire in giving. See resolved goodness felicity shy civility domestic had but.',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per4.jpg',
	},
	{
		id: 5,
		image: '00.jpg',
		catigory: 'Soprt',
		isSponsored: false,
		title: '7 common mistakes everyone makes while traveling',
		text: 'Drawings offended yet answered Jennings perceive laughing six did far. Rooms oh fully taken by worse do. Points afraid but may end law lasted.',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per5.jpg',
	},
	{
		id: 6,
		image: '12.jpg',
		catigory: 'Soprt',
		isSponsored: false,
		title: '5 investment doubts you should clarify',
		text: 'Was out laughter raptures returned outweigh. Luckily cheered colonel I do we attack highest enabled. Tried law yet style child. The bore of true of no be deal.',
		autor: 'John Doe',
		date: 'Jan 22, 2022',
		autor_image: 'per6.jpg',
	},
];
export default TopTodayObject;
